version: '3.8'

services:
  frontend-app:
    build:
      context: .
      args:
        - MS_DESPACHO_PRIVATE_IP=${IP_MS1:-127.0.0.1}
        - MS_VENTAS_PRIVATE_IP=${IP_MS2:-127.0.0.1}
    image: ${REGISTRY:-local}/${REPO:-front_ventas}:latest
    container_name: frontend-app
    restart: always
    ports:
      - "80:8080"