name: CI/CD Frontend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4 

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: front_ventas
          IMAGE_TAG: latest
        run: |
          docker build \
            --build-arg MS_DESPACHO_PRIVATE_IP=${{ secrets.PRIVATE_IP_MS_DESPACHO }} \
            --build-arg MS_VENTAS_PRIVATE_IP=${{ secrets.PRIVATE_IP_MS_VENTAS }} \
            --build-arg MS_VENTAS_PRIVATE_PORT=${{ secrets.PRIVATE_PORT_MS_VENTAS }} \
            --build-arg MS_DESPACHO_PRIVATE_PORT=${{ secrets.PRIVATE_PORT_MS_DESPACHO }} \
            -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
          
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Deploy Frontend vía SSM (Docker Compose)
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO=front_ventas
          COMPOSE_B64=$(cat docker-compose.yaml | base64 -w 0)
          
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Actualizar Frontend con Compose" \
            --parameters "{\"commands\":[
              \"set -e\",
              \"mkdir -p /home/ssm-user/app-frontend\",
              \"cd /home/ssm-user/app-frontend\",
              \"echo $COMPOSE_B64 | base64 -d > docker-compose.yaml\",
              \"aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY\",
              \"export REGISTRY=$REGISTRY\",
              \"export REPO=$REPO\",
              \"export IP_MS1=${{ secrets.PRIVATE_IP_MS_DESPACHO }}\",
              \"export IP_MS2=${{ secrets.PRIVATE_IP_MS_VENTAS }}\",
              \"docker compose pull\",
              \"docker compose up -d\",
              \"docker image prune -f\"
            ]}" \
            --output text
